theme: minima
title: Sryder's Blog
author: Chris Achinga
email: achinga.chris@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write technical articles and share learning resources.

# social links
twitter_username: achinga_chris # DO NOT include the @ character, or else the build will fail!
github_username:  ChrisAchinga # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
